### ISSUE TITLE
Improve name and path of generated Electrod files

### ISSUE THREAD

**Issue by grayswandyr** [nmacedo/Pardinus#1]
It would be nice to generate all .elo files corresponding to a given analysis in a directory, the name of which would depend on the name of the original Electrum file. It would also be nice if this name contained the name of the executed command. E.g. command `check foo` of file `bar.ele` should produce a directory named `bar-check-foo-date-time-NNNN/` (`NNNN` being a fresh id).

**Comment by nmacedo** [comment]
Implemented.

**Comment by grayswandyr** [comment]
Would it be possible to make it such that *file* names are just short strings, e.g. just a 0-padded list of integers, such as `001.elo`, `002.elo`... Sorry about that!
