### ISSUE TITLE
Generation towards Electrod should use and abuse of parentheses

### ISSUE THREAD

**Issue by grayswandyr** [nmacedo/Pardinus#17]
Pretty-printing should parenthesize every kind of term (expressions, formulas, integer expressions). This is to ensure that Electrod parses the generated models consistently (spoiler: as of now, there are cases where it does not and where the fix will not be trivial; besides these problems, this will also ensure that things such as inconsistent operator precedences will not create "artificial" problems).

**Comment by nmacedo** [comment]
Should be better now (with 889e56f0c1a2e9dcddaa14d4eefcfac0075117f6).
